import React,{lazy,Suspense,useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,BarChart3,Bot,BrainCircuit,Building2,Check,CircleUserRound,Cpu,Database,FileText,Layers3,LineChart,Menu,MessageCircleMore,PhoneCall,Route,Settings2,ShieldCheck,ShoppingBag,Sparkles,Users2,WandSparkles,Workflow,X}from'lucide-react';
import'@fontsource-variable/vazirmatn';import'./marketing-v2.css';
import logo from'./assets/brand/rahkar-logo.svg';import automationImage from'./assets/rahkar/service-automation.webp';import customSystemImage from'./assets/rahkar/service-custom-system.webp';import dashboardImage from'./assets/rahkar/service-dashboard.webp';import{addToCart,api}from'./api.js';
const LoginPage=lazy(()=>import('./account.jsx').then(m=>({default:m.LoginPage}))),AccountPage=lazy(()=>import('./account.jsx').then(m=>({default:m.AccountPage}))),CartPage=lazy(()=>import('./account.jsx').then(m=>({default:m.CartPage}))),AdminPage=lazy(()=>import('./account.jsx').then(m=>({default:m.AdminPage}))),SupportAdminPage=lazy(()=>import('./account.jsx').then(m=>({default:m.SupportAdminPage})));
export const serviceProducts=[
{id:'rahkar-ai-automation',name:'هوشمندسازی فرایندهای منابع انسانی',short:'اتوماسیون گردش‌کارهای HR، حذف کارهای تکراری و طراحی دستیارهای هوشمند عملیاتی.',category:'هوش مصنوعی و اتوماسیون',brand:'راهکار',price:0,available_stock:1,product_type:'service',image:automationImage,image_url:automationImage,benefits:['اتوماسیون تأییدها و درخواست‌ها','دستیار هوش مصنوعی اختصاصی','کاهش خطا و زمان پاسخ','ردیابی کامل فرایند']},
{id:'rahkar-custom-platform',name:'طراحی سامانه و ساختار هوشمند سازمانی',short:'سامانه‌ای منطبق با ساختار، نقش‌ها و فرایندهای واقعی سازمان شما.',category:'سامانه اختصاصی',brand:'راهکار',price:0,available_stock:1,product_type:'service',image:customSystemImage,image_url:customSystemImage,benefits:['تحلیل نیاز و طراحی ساختار','سطوح دسترسی چندلایه','پنل کاربر، مدیر و ستاد','استقرار و پشتیبانی']},
{id:'rahkar-smart-dashboard',name:'People Analytics و داشبوردهای هوشمند',short:'تبدیل داده‌های منابع انسانی به بینش مدیریتی، گزارش خودکار و تصمیم‌گیری سریع.',category:'تحلیل داده و داشبورد',brand:'راهکار',price:0,available_stock:1,product_type:'service',image:dashboardImage,image_url:dashboardImage,benefits:['داشبورد مدیریتی چندسطحی','هشدار هوشمند و تحلیل روند','گزارش‌سازی خودکار','اتصال داده‌های موجود']}];
const caps=[[Users2,'منابع انسانی + هوش مصنوعی','داده‌های منابع انسانی را به تصمیم‌های سریع، دقیق و قابل اتکا تبدیل می‌کنیم.'],[Database,'یکپارچه‌سازی داده','داده‌های پراکنده از فایل‌ها، فرم‌ها و سامانه‌های مختلف را در یک ساختار معتبر جمع می‌کنیم.'],[Workflow,'اتوماسیون فرایندها','جذب، آموزش، ارزیابی و درخواست‌های داخلی را هوشمند و قابل پیگیری می‌سازیم.'],[BrainCircuit,'دستیارهای تخصصی AI','Copilot و عامل‌های هوشمند را با دانش و قواعد سازمان شما طراحی می‌کنیم.'],[BarChart3,'People Analytics و داشبورد','شاخص‌ها، پیش‌بینی، هشدار و تحلیل روند را در اختیار مدیران می‌گذاریم.'],[ShieldCheck,'امنیت و حاکمیت داده','هویت، نقش، ثبت رخداد و حفاظت از اطلاعات از ابتدا در معماری لحاظ می‌شود.']];
const uses=[[Sparkles,'AI برای استخدام','غربالگری رزومه، رتبه‌بندی اولیه و پیشنهاد مصاحبه براساس معیارهای سازمان.'],[Bot,'HR ChatGPT','پاسخ‌گویی به کارکنان، تولید مستندات و پاسخ‌های داخلی.'],[Workflow,'اتوماسیون فرایندها','حذف کارهای تکراری در درخواست‌ها، ابلاغ‌ها و گردش تأییدها.'],[FileText,'تولید گزارش','خلاصه‌سازی داده و تولید گزارش مدیریتی همراه با پیشنهاد اقدام.'],[LineChart,'تحلیل داده کارکنان','تحلیل ریسک خروج، مشارکت و روند عملکرد.'],[Cpu,'HR Copilot','دستیار تصمیم‌یار مدیران منابع انسانی برای تصمیم‌های روزانه.']];
const topics=['مشاوره تحول دیجیتال منابع انسانی','طراحی سامانه اختصاصی','People Analytics و داشبورد','هوش مصنوعی و اتوماسیون فرایندها','بازطراحی ساختار و ابزارهای HR'];
const go=p=>{location.hash=p;scrollTo({top:0,behavior:'auto'})};
function Brand({light=false}){return <img className={'brand '+(light?'light':'')} src={logo} alt="راهکار؛ سامانه‌های هوشمند سازمانی"/>}
function Loading(){return <div className="loading"><Brand/><span>در حال آماده‌سازی راهکار…</span></div>}
function Header({route}){const[open,setOpen]=useState(false),section=id=>{setOpen(false);if(route!=='/'){go('/');setTimeout(()=>section(id),80);return}const n=document.getElementById(id);n&&scrollTo({top:n.offsetTop-88,behavior:'smooth'})};return <header><button className="brand-btn" onClick={()=>go('/')}><Brand/></button><nav className={open?'open':''}><button onClick={()=>section('capabilities')}>توانمندی‌ها</button><button onClick={()=>section('dashboards')}>داشبوردها</button><button onClick={()=>section('services')}>خدمات</button><button onClick={()=>section('consultation')}>دریافت مشاوره</button><button onClick={()=>go('/shop')}>فروشگاه خدمات</button></nav><div className="head-actions"><button className="login" onClick={()=>go('/auth/login')}><CircleUserRound/>ورود و ثبت‌نام</button><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
function Hero(){return <section className="hero"><div className="hero-wrap"><div className="hero-copy"><span><Sparkles/>هوش مصنوعی برای منابع انسانی و سامانه‌های سازمانی</span><h1>راهکار، پیوند <em>هوش مصنوعی، منابع انسانی و ساختارهای هوشمند سازمانی</em></h1><p>ما داده‌ها و فرایندهای سازمان را به سامانه‌ها، داشبوردها و دستیارهای هوشمندی تبدیل می‌کنیم که در تصمیم‌گیری و اجرا به کار می‌آیند.</p><div className="hero-actions"><button onClick={()=>document.getElementById('consultation')?.scrollIntoView({behavior:'smooth'})}>دریافت مشاوره<ArrowLeft/></button><button onClick={()=>go('/shop')}>مشاهده خدمات</button></div><div className="proof"><span><Check/>People Analytics</span><span><Check/>سامانه اختصاصی</span><span><Check/>دستیارهای AI</span></div></div><Demo/></div></section>}
function Demo(){return <div className="demo"><div className="dots"><i/><i/><i/></div><div className="demo-title"><div><b>نمای هوش مصنوعی منابع انسانی — ۱۴۰۵</b><span>داشبورد تصمیم‌یار مدیران</span></div><small>AI Assist</small></div><div className="metrics"><article><span>مشارکت کارکنان</span><b>٪۷۸/۴</b></article><article><span>ریسک خروج</span><b>۱۲ نفر</b></article><article><span>توصیه AI</span><b>۳ اقدام</b></article></div><div className="demo-row"><div className="panel"><b>ترکیب واحدها</b>{[84,69,58,47].map((v,i)=><div className="bar" key={v}><small>{['داده و گزارش','عملیات','فروش','پشتیبانی'][i]}</small><span><i style={{width:v+'%'}}/></span></div>)}</div><div className="panel donut-panel"><b>پیش‌بینی وضعیت قرارداد</b><div className="donut"><strong>٪۶۸</strong></div><small>پایدار · نیازمند مداخله</small></div></div><div className="panel trend"><b>روند مشارکت کارکنان</b><div className="line"><i/><i/><i/><i/><i/></div></div><div className="ai-note"><Bot/>هوش مصنوعی پیشنهاد می‌دهد: برای واحد پشتیبانی برنامه نگهداشت و آموزش هدفمند اجرا شود.</div></div>}
function Intro(){return <section className="section"><Heading tag="ماموریت ما" title="تبدیل داده‌های منابع انسانی به تصمیم و سامانه‌های هوشمند" text="تمرکز راهکار روی نقطه اتصال منابع انسانی، هوش مصنوعی و ایجاد ساختارها و سامانه‌های هوشمند است." split/><div className="tri"><Card I={Users2} t="منابع انسانی" p="شناخت فرایندهای HR، نیاز مدیران و تجربه کارکنان."/><Card I={BrainCircuit} t="هوش مصنوعی" p="تحلیل، پیش‌بینی، توصیه‌گری و تولید گزارش."/><Card I={Layers3} t="سامانه هوشمند" p="طراحی ماژول‌ها، سطوح دسترسی و داشبوردهای عملیاتی."/></div></section>}
function Heading({tag,title,text,split=false}){return <div className={'heading '+(split?'split':'')}><div><span>{tag}</span><h2>{title}</h2></div><p>{text}</p></div>}
function Card({I,t,p}){return <article><div className="icon"><I/></div><h3>{t}</h3><p>{p}</p></article>}
function Capabilities(){return <section className="section" id="capabilities"><Heading tag="توانمندی‌ها" title="از تحلیل داده تا ساخت ابزار هوشمند" text="ابزارها و منطق‌های هوشمند متناسب با ساختار و هدف سازمان شما طراحی می‌شوند."/><div className="grid cards">{caps.map(([I,t,p])=><Card key={t} I={I} t={t} p={p}/>)}</div></section>}
function Dashboards(){return <section className="section" id="dashboards"><Heading tag="نمونه داشبوردها" title="تجربه داشبورد و تصمیم‌یار هوشمند" text="هشدار، پیش‌بینی، توصیه و گزارش هوشمند، نقش AI را در تصمیم‌گیری ملموس می‌کند." split/><div className="grid dashboards"><Dash title="People Analytics" sub="تحلیل هوشمند سرمایه انسانی"><div className="mini-metrics"><span>٪۷۱/۵<small>مشارکت</small></span><span>۹ نفر<small>ریسک خروج</small></span><span>۸۲<small>رضایت شغلی</small></span></div><div className="mini-line"><i/><i/><i/><i/><i/></div><footer><Bot/>ریسک خروج تیم فروش بالاتر از میانگین است.</footer></Dash><Dash title="HR Copilot" sub="تصمیم‌یار مدیر منابع انسانی"><div className="checks"><span><Check/>تحلیل علت‌های خروج</span><span><Check/>خلاصه‌سازی پرسشنامه</span><span><Check/>پیشنهاد اقدام اصلاحی</span></div><div className="chat">«افت مشارکت با اضافه‌کاری و ابهام نقش مرتبط است.»</div><footer><WandSparkles/>گزارش مدیریتی با یک کلیک تولید می‌شود.</footer></Dash><Dash title="Smart Workflow" sub="نظارت بر فرایندها"><div className="statuses"><span>۱۸<small>در انتظار</small></span><span>۳۴<small>تأیید امروز</small></span><span>۱/۸ روز<small>زمان پاسخ</small></span></div><div className="kanban"><i>جذب</i><i>آموزش</i><i>ارزیابی</i><i>پرسنلی</i></div><footer><Route/>SLA و هشدارهای تأخیر به‌صورت زنده دیده می‌شود.</footer></Dash></div></section>}
function Dash({title,sub,children}){return <article className="dash"><header><span>{title}</span><b>{sub}</b></header>{children}</article>}
function AI(){return <section className="section ai-section"><Heading tag="هوش مصنوعی در عمل" title="AI، همکار جدید تیم منابع انسانی" text="هوش مصنوعی را در نقاطی به‌کار می‌گیریم که ارزش روزمره و قابل اندازه‌گیری ایجاد کند." split/><div className="grid ai-grid">{uses.map(([I,t,p])=><Card key={t} I={I} t={t} p={p}/>)}</div></section>}
function Services(){return <section className="section" id="services"><Heading tag="خدمات" title="خدماتی که سازمان شما را متحول می‌کند" text="از ساخت سامانه تا تحلیل داده و افزودن لایه هوش مصنوعی به فرایندها."/><div className="grid service-cards">{serviceProducts.map((s,i)=>{const I=[Workflow,Settings2,BarChart3][i];return <article key={s.id}><div className="icon"><I/></div><small>{s.category}</small><h3>{s.name}</h3><p>{s.short}</p><ul>{s.benefits.map(x=><li key={x}><Check/>{x}</li>)}</ul></article>})}</div></section>}
function Consultation(){const[form,setForm]=useState({fullName:'',organization:'',phone:'',topic:topics[0],message:''}),[state,setState]=useState({loading:false,msg:'',error:''});async function submit(e){e.preventDefault();setState({loading:true,msg:'',error:''});try{await api('/consultation-requests',{method:'POST',body:form});setState({loading:false,msg:'درخواست ثبت شد؛ به‌زودی با شما تماس می‌گیریم.',error:''});setForm({fullName:'',organization:'',phone:'',topic:topics[0],message:''})}catch(x){setState({loading:false,msg:'',error:x.message||'ثبت درخواست ناموفق بود.'})}}return <section className="section" id="consultation"><div className="consult"><div className="consult-copy"><span>دریافت مشاوره</span><h2>برای سازمانتان یک مسیر دقیق‌تر طراحی کنیم.</h2><p>اطلاعات خود را ثبت کنید تا درباره منابع انسانی، هوش مصنوعی، داشبورد یا سامانه اختصاصی با شما تماس بگیریم.</p><div className="points"><div><PhoneCall/><span><b>تماس کارشناسی</b><small>شناخت مسئله و دامنه پروژه</small></span></div><div><MessageCircleMore/><span><b>جمع‌آوری نیاز</b><small>ثبت وضعیت فعلی و انتظار سازمان</small></span></div><div><Building2/><span><b>پیشنهاد متناسب</b><small>ارائه مسیر اجرا و مدل همکاری</small></span></div></div></div><form onSubmit={submit}><label>نام و نام خانوادگی<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>نام سازمان<input required value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})}/></label><label>شماره تماس<input required placeholder="09xxxxxxxxx" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>موضوع مشاوره<select value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}>{topics.map(x=><option key={x}>{x}</option>)}</select></label><label>شرح نیاز<textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label>{state.error&&<div className="error">{state.error}</div>}{state.msg&&<div className="success">{state.msg}</div>}<button disabled={state.loading}>{state.loading?'در حال ثبت…':'ثبت درخواست مشاوره'}</button></form></div></section>}
function Store(){const[msg,setMsg]=useState('');function select(s){addToCart(s.id,1);setMsg('درخواست اضافه شد');setTimeout(()=>go('/cart'),400)}return <section className="section store"><div className="grid shop-grid">{serviceProducts.map((s,i)=><article key={s.id}><img src={s.image}/><div><small>{s.category}</small><h3>{s.name}</h3><p>{s.short}</p><button onClick={()=>select(s)}>ثبت درخواست<ArrowLeft/></button></div></article>)}</div>{msg&&<div className="toast">{msg}</div>}</section>}
function Footer(){return <footer><div><Brand light/><p>طراحی سامانه‌های هوشمند سازمانی با تمرکز بر منابع انسانی، داده و هوش مصنوعی.</p></div><nav><button onClick={()=>go('/')}>خانه</button><button onClick={()=>go('/shop')}>خدمات</button><button onClick={()=>go('/auth/login')}>حساب کاربری</button></nav><small>راهکار — سامانه‌های هوشمند سازمانی</small></footer>}
function Home({route}){return <><Header route={route}/><main><Hero/><Intro/><Capabilities/><Dashboards/><AI/><Services/><Consultation/></main><Footer/></>}
function Shop({route}){return <><Header route={route}/><main><section className="shop-hero"><span><ShoppingBag/>فروشگاه خدمات راهکار</span><h1>برای هوشمندسازی سازمان، از یک درخواست روشن شروع کنید.</h1><p>خدمت را انتخاب کنید تا پیشنهاد فنی متناسب با سازمانتان دریافت کنید.</p></section><Store/></main><Footer/></>}
function App(){const[route,setRoute]=useState(()=>location.hash.slice(1)||'/');useEffect(()=>{const f=()=>setRoute(location.hash.slice(1)||'/');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const portal=x=><Suspense fallback={<Loading/>}>{x}</Suspense>;if(route==='/auth/login'||route==='/auth/verify')return portal(<LoginPage navigate={go}/>);if(route==='/cart'||route==='/checkout')return portal(<CartPage products={serviceProducts} navigate={go}/>);if(route.startsWith('/account')||route.startsWith('/payment/result'))return portal(<AccountPage route={route} navigate={go}/>);if(route==='/admin/support')return portal(<SupportAdminPage navigate={go}/>);if(route==='/admin')return portal(<AdminPage navigate={go}/>);return route==='/shop'?<Shop route={route}/>:<Home route={route}/>}
createRoot(document.getElementById('root')).render(<App/>);
